[project]
name = "todos"
version = "1.0.0"
description = "Voting data from Folketinget."
dependencies = [
    "flask (==3.1.1)",
    "psycopg2 (==2.9.10)",
    "pandas (==2.2.3)",
    "SQLAlchemy (==2.0.41)"
]

[tool.setuptools]
py-modules = []
